version: '3.8'

services:
  # Backend service for development
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: stuffhappens-server-dev:latest
    container_name: stuffhappens-server-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules
      - server_data_dev:/app/db
    restart: unless-stopped
    command: npm run dev

  # Frontend service for development
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: stuffhappens-client-dev:latest
    container_name: stuffhappens-client-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - server

volumes:
  server_data_dev:
    driver: local 