services:
  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: stuffhappens-server-prod:latest
    container_name: stuffhappens-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    # Remove volumes completely - database is included in the image
    # volumes:
    #   - server_data:/app/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: stuffhappens-client-prod:latest
    container_name: stuffhappens-client
    ports:
      - "5173:80"
    depends_on:
      - server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

# Volumes removed - database is included in the image
# volumes:
#   server_data:
#     driver: local 